
on:
  push:
    branches:
      - master



permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: Apistories20231004
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: '7.0'   

jobs:
  build:
    if: github.ref == 'refs/heads/master' 
    runs-on: ubuntu-latest

    steps:

      # Checkout the repo
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      

      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build and publish
      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test
          dotnet publish -c Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/ghactions' 
      
      # Deploy to Azure Web apps
      
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Api/ghactions'
      
      - name: logout
        run: |
          az logout
