name: CICD
on:
  push:
    branches:
      - master
permissions:
      id-token: write
      contents: read
env:
  AZURE_WEBAPP_NAME: Apistories20231004
  AZURE_WEBAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: '7.0'   
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Setup .NET Core
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: ${{ env.DOTNET_VERSION }} 
          - name: Build and publish
            run: |
              dotnet restore
              dotnet build --configuration Release
              dotnet test
              dotnet publish --configuration Release --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Api' 
          - uses: actions/upload-artifact@v3
            with: 
                name: publish-artifact
                path: path/to/artifact/
                if-no-files-found: error

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Az login
            uses: azure/login@v1
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          - name: Deploy
            uses: azure/webapps-deploy@v2
            with: 
              app-name: ${{ env.AZURE_WEBAPP_NAME }}
              package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Api'
          - name: Logout
            run: az logout
